project:
  type: website
  output-dir: docs

website:
  title: "Peter MacPherson"
  site-url: "https://petermacpherson.github.io"
  navbar:
    left:
      - text: "About"
        href: about.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Publications"
        href: publications.qmd
  page-footer:
    left: "Licensed under a [CC-BY 4.0 International License](https://creativecommons.org/licenses/by/4.0/)"
    right: "Built with [Quarto](https://quarto.org)"

format:
  html:
    theme: cosmo
    css: styles.scss
    toc: false
    include-in-header: contact-icons.html

